## Numpy in Python

* is a fundamental library for scientific computing in python.
* it provides support for *arrays* and *matrices* along with a collection of mathematical functions operate on these data structures.

#### **Install Numpy in Pyhton**
* !pip install numpy

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [5]:
## 0 dimenstional array
arr0 = np.array(5)

print(type(arr0))

print(arr0.ndim)

<class 'numpy.ndarray'>
0


In [ ]:
## create array using numpy

## 1D array
arr1 = np.array([2,1,4,3,5,6])
print(type(arr1))
print(arr1.shape) ## tells no. of element and dimention of array
print(arr1.dtype) ## int64 : system based

print(arr1.ndim)  ## 1 dimention

<class 'numpy.ndarray'>
(6,)
int64
1


In [ ]:
## reshape arr1 into 1-Dimentional array

arr2 = np.array([2,1,4,3,5,6])
print(arr2.shape)  ## row and col  ->  output: (6,) indicate 1D array with 6 element

print("dimention of arr :",arr2.ndim)

(6,)
dimention of arr : 1


In [ ]:
arr3 = np.array([[2,3,4],
                 [5,6,7]])

display(arr3)

print(arr3)
print('shape of array : ',arr3.shape)   ## (2, 3)  2-rows and 3-cols



print("dimention of arr :",arr3.ndim)

array([[2, 3, 4],
       [5, 6, 7]])

[[2 3 4]
 [5 6 7]]
shape of array :  (2, 3)
dimention of arr : 2


In [53]:
## arange(start, stop, steps, dtype=None) function

arr1 = np.arange(5)
print(arr1)  # [0 1 2 3 4]

arr2 = np.arange(2, 6)
print(arr2)  # [2 3 4 5]

arr3 = np.arange(2, 7, 2)
print(arr3)

arr4 = np.arange(2, 9, 3, dtype=float)
print(arr4)


[0 1 2 3 4]
[2 3 4 5]
[2 4 6]
[2. 5. 8.]


In [55]:
## arrange the numbers from 1 to 12 in 1D array
arr1 = np.arange(1, 13)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [56]:
## arrange the numbers from 1 to 12 in 2D (3 row and 4 col) array
arr2 = np.arange(1, 13).reshape(3, 4)  
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [58]:
## arrange the numbers from 1 to 12 in 2D (6 row and 2 col) array
arr3 = np.arange(1, 13).reshape(6, 2)  
print(arr3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [61]:
## arrange the numbers from 1 to 5 in 2D (5 row and 1 col) array
arr4 = np.arange(1, 6).reshape(5, 1)  
print(arr4)
print(type(arr4))

[[1]
 [2]
 [3]
 [4]
 [5]]
<class 'numpy.ndarray'>


In [77]:
x = 2
y = (2,)
z = (2,3)
a = (2,3,4)

print(type(x))
print(type(y))
print(type(z))
print(type(a))


<class 'int'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>


In [81]:
arr = np.array([[1,2,3],
               [4,5,6]])

print("array :\n",arr)
print()
print('shape : ',arr.shape)
print('dimensions : ',arr.ndim)
print('Size(No. of element) : ', arr.size)
print('Data types : ', arr.dtype)
print('Item size (in bytes) : ', arr.itemsize)

array :
 [[1 2 3]
 [4 5 6]]

shape :  (2, 3)
dimensions :  2
Size(No. of element) :  6
Data types :  int64
Item size (in bytes) :  8


In [ ]:
## ones(row, col) :- every element generate into 1
arr1 = np.ones(3, dtype=int)  ## by default dtype=float
print(arr1)

[1 1 1]


In [75]:
arr2 = np.ones((3, 4))   ## 3 row and 4 col
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [74]:
arr3 = np.ones((3, 4, 2))   ## 3 2D array with (4 row and 2 col)
print(arr3)


[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [84]:
## eye(order) : identity matrix

identity_matrix = np.eye(3, dtype=int)  # dtype is optinal, by default it is float
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [86]:
## numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

### Element wise addition
print("addition : ", arr1+arr2)

### Element wise subtraction
print("addition : ", arr1-arr2)

### Element wise multiplication
print("addition : ", arr1*arr2)

### Element wise division
print("addition : ", arr1/arr2)

addition :  [6 6 6 6 6]
addition :  [-4 -2  0  2  4]
addition :  [5 8 9 8 5]
addition :  [0.2 0.5 1.  2.  5. ]


In [93]:
## Univesal Function

arr = np.array([1,2,3,4,5])

### square root
print(np.sqrt(arr))

### exponential
print(np.exp(arr))

### sine(angle)
print(np.sin(arr))

### natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [94]:
## Array slicing and indexing

arr = np.array([2,3,4,7,8,9])
print(arr[0])
print(arr[-1])

2
9


In [96]:
arr = np.array([[1,2,3,4],
                [5,6,4,3],
                [2,5,1,7]])

print('Array :\n',arr)

Array :
 [[1 2 3 4]
 [5 6 4 3]
 [2 5 1 7]]


In [108]:
arr = np.array([[1,2,3,4],
                [5,6,4,3],
                [2,5,1,7]])

print(arr[0][0])
print()

print(arr[1:, 2:])
print()

print(arr[0:2, 0:2])
print()

print(arr[0:2, 0:])

1

[[4 3]
 [1 7]]

[[1 2]
 [5 6]]

[[1 2 3 4]
 [5 6 4 3]]


In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 4, 3],
                [2, 5, 1, 7]])

arr[1:, 2:] = 99

print(arr)

[[ 1  2  3  4]
 [ 5  6 99 99]
 [ 2  5 99 99]]


In [123]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 4, 3],
                [2, 5, 1, 7]])

print(arr)
print()
arr[1:, 2:] = arr[1:, 2:]*3

print(arr)

[[1 2 3 4]
 [5 6 4 3]
 [2 5 1 7]]

[[ 1  2  3  4]
 [ 5  6 12  9]
 [ 2  5  3 21]]


In [125]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 4, 3],
                [2, 5, 1, 7]])
print(arr)
print()

arr[1:, 0:] = 100

print(arr)

[[1 2 3 4]
 [5 6 4 3]
 [2 5 1 7]]

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [134]:
## statistics of given data

data = np.array([1,2,3,4,5,6,7,8,9])

### mean
print('Mean', np.mean(data))

### median
print(np.median(data))

### standard_deviation
print(np.std(data))

### variance
print(np.var(data))

Mean 5.0
5.0
2.581988897471611
6.666666666666667


In [140]:
## statistical concept - Normailzation

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalization = (data - mean) / std_dev

print("Normalized data : ", normalization)

Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [144]:
data = np.array([2,3,4,5,6,7,8,9])

print(data < 5)

print((data>=4) & (data<=7))

[ True  True  True False False False False False]
[False False  True  True  True  True False False]
